import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { Ubuntu } from 'next/font/google';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ['300', '400', '500', '700'],
  variable: '--font-ubuntu'
})

export const metadata: Metadata = {
  title: 'Social Media Monitoring',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={ubuntu.className}>{children}</body> */}
      <body className="font-ubuntu">{children}</body>
    </html>
  )
}
